In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
# install micromamba
!curl -Ls https://micro.mamba.pm/api/micromamba/linux-64/latest | tar -xvj bin/micromamba

bin/micromamba


In [3]:
!./bin/micromamba create -y -n ast310 python=3.11.14


[+] 0.0s
[+] 0.1s
[+] 0.2s
conda-forge/linux-64   3%
conda-forge/noarch     6%[+] 0.3s
conda-forge/linux-64  14%
conda-forge/noarch    30%[+] 0.4s
conda-forge/linux-64  26%
conda-forge/noarch    53%[+] 0.5s
conda-forge/linux-64  37%
conda-forge/noarch    77%[+] 0.6s
conda-forge/linux-64  43%
conda-forge/noarch   100%conda-forge/noarch                                
[+] 0.7s
conda-forge/linux-64  60%[+] 0.8s
conda-forge/linux-64  82%[+] 0.9s
conda-forge/linux-64  93%[+] 1.0s
conda-forge/linux-64  93%[+] 1.1s
conda-forge/linux-64  93%conda-forge/linux-64                              


Transaction

  Prefix: /root/.local/share/mamba/envs/ast310

  Updating specs:

   - python=3.11.14


  Package              Version  Build                 Channel          Size
─────────────────────────────────────────────────────────────────────────────
  Install:
─────────────────────────────────────────────────────────────────────────────

  + _libgcc_mutex          0.1  conda_forge           conda-fo

In [4]:
!export PATH=/content/bin:$PATH && micromamba run -n ast310 python --version

Python 3.11.14


In [ ]:
%ls

bin/  drive/  sample_data/


In [5]:
!export PATH=/content/bin:$PATH && micromamba run -n ast310 pip install mutagen

In [6]:
!export PATH=/content/bin:$PATH && micromamba run -n ast310 pip install -r /content/drive/MyDrive/GraFP/prova.txt


  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.3/18.3 MB 147.6 MB/s  0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 38.4/38.4 MB 115.6 MB/s  0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 23.8/23.8 MB 104.6 MB/s  0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.6/6.6 MB 147.3 MB/s  0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.3/3.3 MB 149.6 MB/s  0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 534.5/534.5 kB 24.8 MB/s  0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.3/56.3 MB 90.2 MB/s  0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 536.2/536.2 kB 28.1 MB/s  0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 109.6 MB/s  0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.7/3.7 MB 55.9 MB/s  0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.0/7.0 MB 147.5 MB/s  0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━

In [7]:
%cd /content/drive/MyDrive/GraFP

/content/drive/.shortcut-targets-by-id/1suc2HZBEmgYV_AfH3YEB6lDfyHuc-ofZ/GraFP


In [ ]:
!export PATH=/content/bin:$PATH && micromamba run -n ast310 python /content/drive/MyDrive/GraFP/generate.py --test_dir /content/drive/MyDrive/GraFP/fma_mini

In [18]:
!export PATH=/content/bin:$PATH && micromamba run -n ast310 python /content/drive/MyDrive/GraFP/test_fp.py --test_dir data/fma_mini.json --n_query_db 80

Traceback (most recent call last):
  File "/content/drive/MyDrive/GraFP/test_fp.py", line 26, in <module>
    from encoder.graph_encoder import GraphEncoder
  File "/content/drive/.shortcut-targets-by-id/1suc2HZBEmgYV_AfH3YEB6lDfyHuc-ofZ/GraFP/encoder/graph_encoder.py", line 7, in <module>
    from timm.models.layers import DropPath
  File "/root/.local/share/mamba/envs/ast310/lib/python3.11/site-packages/timm/__init__.py", line 3, in <module>
    from .models import create_model, list_models, list_pretrained, is_model, list_modules, model_entrypoint, \
  File "/root/.local/share/mamba/envs/ast310/lib/python3.11/site-packages/timm/models/__init__.py", line 34, in <module>
    from .levit import *
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  Fil

In [37]:
!export PATH=/content/bin:$PATH && micromamba run -n ast310 python /content/drive/MyDrive/GraFP/query.py --test_ids all --test_dir fma_mini/002

Creating new model...
Creating dataloaders ...
path is fma_mini/002
=>Loading indices from fma_mini/002
Loading indices from data/002.json
Loaded 3 files from fma_mini/002
=> loading checkpoint '/content/drive/MyDrive/GraFP/checkpoint/model_tc_27_best.pth'
=> Creating query and db fingerprints...
Step [0/3]	 shape: torch.Size([302, 128])
Step [1/3]	 shape: torch.Size([302, 128])
Step [2/3]	 shape: torch.Size([303, 128])
Load 907 items from inference/1768935601/query.mm.
Load 907 metadata items from inference/1768935601/metadata.npy.
Load 30,234 items from /content/drive/MyDrive/GraFP/logs/store/small/model_tc_27_best/dummy_db.mm.
Load 30,234 metadata items from /content/drive/MyDrive/GraFP/logs/store/small/model_tc_27_best/dummy_db_metadata.npy.
Creating index: ivfpq
Training index...
Elapsed time: 3.45 seconds.
30234 items from dummy DB
test_id: all,  n_test: 888
[[(['Kodak Ghosts'], array(['....like bacon sundays'], dtype='<U22')), (['Kodak Ghosts'], array(['....like bacon sundays'],

Load 54,426 items from logs/store/small/model_tc_27_best/query.mm.
Load 54,426 metadata items from logs/store/small/model_tc_27_best/metadata.npy.
Traceback (most recent call last):
  File "/content/drive/MyDrive/GraFP/query.py", line 244, in <module>
    main()
  File "/content/drive/MyDrive/GraFP/query.py", line 236, in main
    predict_query(emb_dir=fp_dir,
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/content/drive/MyDrive/GraFP/query.py", line 64, in predict_query
    dummy_db, dummy_db_shape, dummy_db_metadata = load_memmap_data(emb_dummy_dir, 'dummy_db')
                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/content/drive/.shortcut-targets-by-id/1suc2HZBEmgYV_AfH3YEB6lDfyHuc-ofZ/GraFP/eval.py", line 166, in load_memmap_data
    path_shape = os.path.join(source_dir, fname + '_shape.npy')
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen posixpath>", line 76, in join
TypeError: expected str, bytes or os.PathLike object, not NoneType

In [ ]:
import numpy as np

arr = np.load("/content/drive/MyDrive/GraFP/logs/store/small/model_tc_27_best/0b2093c6/hit_rates.npy")
print(arr)


[[72.   80.75 85.8  89.   89.65 92.2 ]
 [91.1  93.75 95.75 97.6  98.05 98.85]
 [91.45 95.1  96.75 98.15 98.65 99.05]
 [94.85 97.3  98.4  99.15 99.6  99.8 ]]


In [ ]:
arr = np.load("/content/drive/MyDrive/GraFP/logs/store/small/model_tc_27_best/0b2093c6/gt_ids.npy")
print(arr[:20])

[36372 36311 51428 39769 39102 51783 53302 39274 46108 34492 51326 46166
 45636 39664 35183 51712 46855 52407 39510 32155]


In [ ]:
arr = np.load("/content/drive/MyDrive/GraFP/logs/store/small/model_tc_27_best/0b2093c6/pred_ids.npy")
print(arr[:20])

[[36371 36371 36371 36371 36371 36371]
 [36311 36311 36311 36311 36311 36311]
 [51429 51429 51428 51428 51428 51428]
 [39768 39768 39768 39769 39769 39769]
 [39102 39102 39102 39102 39102 39102]
 [51784 51783 51783 51783 51783 51783]
 [53302 53302 53302 53302 53302 53302]
 [39274 39274 39274 39274 39274 39274]
 [46108 46108 46108 46108 46108 46108]
 [34491 34492 34492 34492 34492 34492]
 [51325 51325 51325 51325 51325 51326]
 [46166 46166 46166 46166 46166 46166]
 [45635 45635 45635 45635 45635 45635]
 [39664 39664 39664 39664 39664 39664]
 [35183 35182 35182 35183 35182 35182]
 [51712 51712 51712 51712 51712 51712]
 [46855 46855 46855 46855 46855 46855]
 [52407 52407 52407 52407 52407 52407]
 [39510 39510 39510 39510 39510 39510]
 [32155 32155 32155 32155 32155 32155]]
