In [20]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [21]:
# install micromamba
!curl -Ls https://micro.mamba.pm/api/micromamba/linux-64/latest | tar -xvj bin/micromamba

bin/micromamba


In [22]:
!./bin/micromamba create -y -n ast310 python=3.11.14


[+] 0.0s
[+] 0.1s
conda-forge/linux-64  ⣾  
conda-forge/noarch    ⣾  [+] 0.2s
conda-forge/linux-64   3%
conda-forge/noarch    15%[+] 0.3s
conda-forge/linux-64  16%
conda-forge/noarch    40%[+] 0.4s
conda-forge/linux-64  27%
conda-forge/noarch    64%[+] 0.5s
conda-forge/linux-64  39%
conda-forge/noarch    89%conda-forge/noarch                                
[+] 0.6s
conda-forge/linux-64  46%[+] 0.7s
conda-forge/linux-64  55%[+] 0.8s
conda-forge/linux-64  71%[+] 0.9s
conda-forge/linux-64  88%[+] 1.0s
conda-forge/linux-64  98%conda-forge/linux-64                              
[+] 1.1s


Transaction

  Prefix: /root/.local/share/mamba/envs/ast310

  Updating specs:

   - python=3.11.14


  Package              Version  Build                 Channel           Size
──────────────────────────────────────────────────────────────────────────────
  Install:
──────────────────────────────────────────────────────────────────────────────

  + _libgcc_mutex          0.1  conda_forge           conda

In [24]:
!export PATH=/content/bin:$PATH && micromamba run -n ast310 python --version

Python 3.11.14


In [ ]:
%ls

bin/  drive/  sample_data/


In [25]:
!export PATH=/content/bin:$PATH && micromamba run -n ast310 pip install mutagen

  Using cached mutagen-1.47.0-py3-none-any.whl.metadata (1.7 kB)
Using cached mutagen-1.47.0-py3-none-any.whl (194 kB)


In [26]:
!export PATH=/content/bin:$PATH && micromamba run -n ast310 pip install -r /content/drive/MyDrive/GraFP/prova.txt


  Using cached absl_py-2.3.1-py3-none-any.whl.metadata (3.3 kB)
  Using cached anyio-4.12.1-py3-none-any.whl.metadata (4.3 kB)
  Using cached audiomentations-0.37.0-py3-none-any.whl.metadata (11 kB)
  Using cached audioread-3.1.0-py3-none-any.whl.metadata (9.0 kB)
  Using cached certifi-2026.1.4-py3-none-any.whl.metadata (2.5 kB)
  Using cached cffi-2.0.0-cp311-cp311-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (2.6 kB)
  Using cached charset_normalizer-3.4.4-cp311-cp311-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (37 kB)
  Using cached click-8.3.1-py3-none-any.whl.metadata (2.6 kB)
  Using cached decorator-5.2.1-py3-none-any.whl.metadata (3.9 kB)
  Using cached faiss_cpu-1.13.2-cp310-abi3-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (7.6 kB)
  Using cached filelock-3.20.3-py3-none-any.whl.metadata (2.1 kB)
  Using cached fsspec-2026.1.0-py3-none-any.whl.metadata (10 kB)
  Using cached grpcio-1.76.0-cp311-cp311-manylinux2014_x86_

In [27]:
%cd /content/drive/MyDrive/GraFP

/content/drive/.shortcut-targets-by-id/1suc2HZBEmgYV_AfH3YEB6lDfyHuc-ofZ/GraFP


In [ ]:
!export PATH=/content/bin:$PATH && micromamba run -n ast310 python /content/drive/MyDrive/GraFP/generate.py --test_dir /content/drive/MyDrive/GraFP/fma_mini

Loading model...
path is /content/drive/MyDrive/GraFP/fma_mini
=>Loading indices from /content/drive/MyDrive/GraFP/fma_mini
Loaded 180 files from /content/drive/MyDrive/GraFP/fma_mini
/root/.local/share/mamba/envs/ast310/lib/python3.11/site-packages/torch_audiomentations/core/composition.py:42: FutureWarning: Transforms now expect an `output_type` argument that currently defaults to 'tensor', will default to 'dict' in v0.12, and will be removed in v0.13. Make sure to update your code to something like:
  >>> augment = Compose(..., output_type='dict')
  >>> augmented_samples = augment(samples).samples
  warnings.warn(
Loading checkpoint...
=> loading checkpoint '/content/drive/MyDrive/GraFP/checkpoint/model_tc_27_best.pth'
Traceback (most recent call last):
  File "/content/drive/MyDrive/GraFP/generate.py", line 105, in <module>
    main()
  File "/content/drive/MyDrive/GraFP/generate.py", line 93, in main
    checkpoint = torch.load(ckp)
                 ^^^^^^^^^^^^^^^
  File "/root/.

In [33]:
!export PATH=/content/bin:$PATH && micromamba run -n ast310 python /content/drive/MyDrive/GraFP/test_fp.py --test_dir data/fma_mini.json --n_query_db 80

Creating new model...
Creating dataloaders ...
path is data/fma_mini.json
=>Loading indices from index file data/fma_mini.json
Loaded 180 files from data/fma_mini.json
Creating dummy db with 100 samples and query db with 80 samples
dict_items([('tc_27', ['best']), ('tc_29', ['best']), ('tc_30', ['best']), ('tc_31', [360]), ('tc9', ['best']), ('tc10', [275]), ('tc11', [350]), ('tc12', [325])])
=> loading checkpoint '/content/drive/MyDrive/GraFP/checkpoint/model_tc_27_best.pth'
Load 24,192 items from logs/store/small/model_tc_27_best/query.mm.
Load 24,192 metadata items from logs/store/small/model_tc_27_best/metadata.npy.
Load 24,192 items from logs/store/small/model_tc_27_best/db.mm.
Load 24,192 metadata items from logs/store/small/model_tc_27_best/metadata.npy.
Load 30,234 items from logs/store/small/model_tc_27_best/dummy_db.mm.
Load 30,234 metadata items from logs/store/small/model_tc_27_best/dummy_db_metadata.npy.
Creating index: ivfpq
Training index...
Traceback (most recent call l

In [ ]:
import numpy as np

arr = np.load("/content/drive/MyDrive/GraFP/logs/store/small/model_tc_27_best/0b2093c6/hit_rates.npy")
print(arr)


[[72.   80.75 85.8  89.   89.65 92.2 ]
 [91.1  93.75 95.75 97.6  98.05 98.85]
 [91.45 95.1  96.75 98.15 98.65 99.05]
 [94.85 97.3  98.4  99.15 99.6  99.8 ]]


In [ ]:
arr = np.load("/content/drive/MyDrive/GraFP/logs/store/small/model_tc_27_best/0b2093c6/gt_ids.npy")
print(arr[:20])

[36372 36311 51428 39769 39102 51783 53302 39274 46108 34492 51326 46166
 45636 39664 35183 51712 46855 52407 39510 32155]


In [ ]:
arr = np.load("/content/drive/MyDrive/GraFP/logs/store/small/model_tc_27_best/0b2093c6/pred_ids.npy")
print(arr[:20])

[[36371 36371 36371 36371 36371 36371]
 [36311 36311 36311 36311 36311 36311]
 [51429 51429 51428 51428 51428 51428]
 [39768 39768 39768 39769 39769 39769]
 [39102 39102 39102 39102 39102 39102]
 [51784 51783 51783 51783 51783 51783]
 [53302 53302 53302 53302 53302 53302]
 [39274 39274 39274 39274 39274 39274]
 [46108 46108 46108 46108 46108 46108]
 [34491 34492 34492 34492 34492 34492]
 [51325 51325 51325 51325 51325 51326]
 [46166 46166 46166 46166 46166 46166]
 [45635 45635 45635 45635 45635 45635]
 [39664 39664 39664 39664 39664 39664]
 [35183 35182 35182 35183 35182 35182]
 [51712 51712 51712 51712 51712 51712]
 [46855 46855 46855 46855 46855 46855]
 [52407 52407 52407 52407 52407 52407]
 [39510 39510 39510 39510 39510 39510]
 [32155 32155 32155 32155 32155 32155]]
